
'use server';

/**
 * @fileOverview An AI agent for generating product descriptions.
 * This file contains the full Genkit flow for generating a product description based on fabric properties.
 *
 * - generateProductDescription - A function that generates a product description.
 * - GenerateProductDescriptionInput - The input type for the generateProductDescription function.
 * - GenerateProductDescriptionOutput - The return type for the generateProductDescription function.
 */

import { genkit } from 'genkit';
import { googleAI } from '@genkit-ai/googleai';
import { z } from 'genkit/zod';
import 'dotenv/config';

// Initialize Genkit and configure plugins in one place.
// This `ai` object will be used to define prompts and flows.
const ai = genkit({
  plugins: [
    googleAI({
      apiKey: process.env.GEMINI_API_KEY,
    }),
  ],
  logLevel: 'debug',
  enableTracing: true,
});

// Define the schema for the input data using Zod.
const GenerateProductDescriptionInputSchema = z.object({
  fabricName: z.string().describe('The name of the fabric.'),
  keyProperties: z
    .string()
    .describe(
      'Key properties of the fabric, such as material composition, weave, weight, and finish.'
    ),
});
export type GenerateProductDescriptionInput = z.infer<
  typeof GenerateProductDescriptionInputSchema
>;

// Define the schema for the output data using Zod.
const GenerateProductDescriptionOutputSchema = z.object({
  description: z.string().describe('A compelling and informative product description.'),
});
export type GenerateProductDescriptionOutput = z.infer<
  typeof GenerateProductDescriptionOutputSchema
>;

// Define the prompt that will be sent to the AI model.
const productDescriptionPrompt = ai.definePrompt({
  name: 'generateProductDescriptionPrompt',
  input: { schema: GenerateProductDescriptionInputSchema },
  output: { schema: GenerateProductDescriptionOutputSchema },
  prompt: `You are an expert copywriter specializing in product descriptions for fabrics.

  Based on the fabric name and its key properties, create a compelling and informative product description in Indonesian that highlights its features and benefits.

  Fabric Name: {{{fabricName}}}
  Key Properties: {{{keyProperties}}}`,
});

// Define the main flow that orchestrates the AI call.
const generateProductDescriptionFlow = ai.defineFlow(
  {
    name: 'generateProductDescriptionFlow',
    inputSchema: GenerateProductDescriptionInputSchema,
    outputSchema: GenerateProductDescriptionOutputSchema,
  },
  async (input) => {
    const { output } = await productDescriptionPrompt(input);

    if (!output) {
      throw new Error('No output generated by the language model.');
    }
    
    return output;
  }
);


// Export a single function to be called from the application UI.
// This function acts as a clean entry point to the Genkit flow.
export async function generateProductDescription(
  input: GenerateProductDescriptionInput
): Promise<GenerateProductDescriptionOutput> {
  return generateProductDescriptionFlow(input);
}
